### PR TITLE
Json api

### PR DESCRIPTION
**Pull request by martinclaus**

### CODE REVIEW

**Comment by maxfischer2781** [comment]
Just for reference (since there are many unrelated formatting changes) did you apply a code formatter?

**Comment by martinclaus** [comment]
I formatted the code such that flake8 runs quietly.

**Comment by maxfischer2781** [comment]
Please revert the formatting changes. It is very difficult to review the relevant changes in this noise.

I am open for a separate PR on code formatting.

**Comment by maxfischer2781** [comment]
@martinclaus are you interested in taking over maintenance of this module? Feel free to use a forked repo instead of this, I can give you access to the PyPI project if you adjust the metadata to list you as the maintainer.

Since my institution has stopped using SixPay via Indico, I cannot make any tests and I'm not feeling confident enough to do e-payment just based on code review.

**Pull request closed without merging**
